### ISSUE TITLE
(more strongly?) differentiate moving circles from edit circles

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/svg-detailer#1]
when I mouse over a created circle (for example)
    then I see some gray circles
       the center gray circle has different meaning, grabbing it and dragging moves the whole object
           differentiate it in style from the other gray circles that alter the path itself 

also rectangles

**Comment by jrflood** [comment]
Part of this disconnect derives from the sometimes peculiar and inconsistent way SVG elements are defined.

Circles, ellipses, rectangles, and text all have specifically defined origin points.  If you “edit” one of them, the element moves.

More later . . .

**Comment by jrflood** [comment]
By (SVG) convention, a few point-origined shapes (rectangle, circle, ellipse, text) have a defined point of origin.  The rectangle's origin point is its upper left corner, and the circle's origin is its center.  These are articulated on the bubble mouseover by the crossed double arrow cursor.

**Comment by jrflood** [comment]
Recently, "shift" bubbles for shapes without intrinsic origin points have been added.  The previous origin points for rectangle, circle, ellipse, and text have been conformed to the new form and behavior.  The new shift bubble is about 50% larger than other user-created points, and is a dark teal color.  For the elements without intrinsic origin points, the shift bubble is centroidal (although in the case of quadratic and cubics, only approximately).
