### ISSUE TITLE
Multi-line text breaks moving the object

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/svg-detailer#11]

**Comment by jrflood** [comment]
The current implementation of text creates a new text element the encompassing group, offset vertically by textHeight.  Unfortunately, this does not get handled properly by the shift element state.  Possible remedies are: 1) additional articulation in the text case; 2) use of <tspan> elements after first text element; 3) SVG 2 not ready for primetime yet?

**Comment by jrflood** [comment]
Original (pre-ES6) code handles this case, but failed due to undefined var when executed.  Another bug exposed for this case, regarding element conflict, so not complete yet.
