### ISSUE TITLE
Add ability to scale line thickness based on canvas (window?) size

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/svg-detailer#7]

**Comment by jrflood** [comment]
As defined, the stroke-width defaults to one pixel.  However, the scale/zoom level of the image in the <svg> element will change the image-pixel width of the stroke such that it renders in the screen pixel space as one pixel width.

This means that the stroke-width attribute of the svg element created will likely be some non-integer number which is not 1.
Experiments are ongoing to evaluate the use of an unscaled stroke-width attribute.  In other words, not scaled by zoom at initialization.

**Comment by jrflood** [comment]
Attribute stroke-width is no longer recomputed by the initialization code.  The default is 1.  An API-ish function will be created to set an arbitrary value.

**Comment by jrflood** [comment]
API feature added.
