### ISSUE TITLE
All shapes should only render fill

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/svg-detailer#8]
* [x] including arrowhead

**Comment by jrflood** [comment]
A stroke-width attribute value of 1 with the same color and opacity of the fill attribute produced no visible difference in the rendered filled shape.

**Comment by jrflood** [comment]
Generally, setting SVG element CSS class attributes such that the stroke and stroke-opacity are the same as the fill and fill-opacity produces a rendered shape with no distinguishable "outline".  CSS inheritance causes unintended styling of (edit/bubbles) circles for SVG circle elements.  Polygon stroke is not overridden until element is complete for some reason.

**Comment by jrflood** [comment]
For TW usage where the intent is to render shapes filled, the general pattern for overriding created svg elements is to include in the <style> section:

g.polyline polyline {
  fill:#555555;
  fill-opacity: 0.7;
  stroke "555555;
  stroke-opacity: 0.7;
}
For idiosyncratic compound elements:
g.arrow line {
  stroke: teal;
  stroke-opacity: 0.6;
}
g.arrow polygon {
  stroke: teal;
  stroke-opacity: 0.6;
}

**Comment by jrflood** [comment]
Adopting a convention like this will allow creation of SVG without distracting behavior such as invisible lines during creation of line-segment-based graphic elements.
